config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root to: 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all.order('updated_at DESC')
  end

  def show
  end

  def new
    @item = current_user.items.build
  end

  def edit
  end

  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:title, :description, :external_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :external_link
    = f.text_field :external_link
  .actions = f.submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'|
= link_to 'Back', items_path

app/views/items/index.html.slim
ol
  - @items.each do |item|
    li
      p
        - if item.external_link?
          a href="#{item.external_link}"
            = item.title
        - else
          =link_to item.title, item_path(item)
      span
        ul
          li
            = link_to item, class: 'btn-floating blue left' do
              i.material-icons attach_file
          li
            = link_to edit_item_path(item), class: 'btn-floating green left' do
              i.material-icons insert_chart
          li
            = link_to item, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn-floating red' do
              i.material-icons publish

br

= link_to new_item_path, class: 'btn-floating btn-large wave-effect waves-light red' do
  i.material-icons add

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
p#notice = notice

p
  strong Title:
  = @item.title
p
  strong Description:
  = @item.description
p
  strong External link:
  = @item.external_link

= link_to 'Edit', edit_item_path(@item)
'|
= link_to 'Back', items_path

app/views/layouts/application.html.slim
html
  head
    title HackernewClone
    = csrf_meta_tags
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  body
    nav.red role='navigation'
      .nav-wrapper.container
        = link_to 'Hackernews Clone', root_path, class: 'brand-logo'
    .container
      p.notice=notice
      p.alert=alert
      = yield